baseURL: https://bpdiale.netlify.app
languageCode: en-us
theme: aafu
params:
  aboutme:
    description: Experienced radiation scientist with a demonstrated history of working in the regulatory environment. Skilled in radiation safety,analytical skills, LaTex, R programming and Microsoft Package. Strong administrative administrative professional with a Master of Science - MSc focused in Nuclear Medicine from Stellenbosch University.
    icon: fas fa-user
    title: About Me
  author: Darshan Baral
  copyright: Rorireo copyright
  description: Website title
  education:
    icon: fas fa-graduation-cap
    list:
      - college: Stellenbosch University
        dates: 2017 - 2020
        degree: Master of Science - MS, Nuclear Medicine
        thesis_title: 'Influence of acquisition time and smoothing parameters on Ga-68 wholebody PET/CT image quality.'
        thesis_url: 'http://hdl.handle.net/10019.1/109341'
      - college: University of Limpopo - Medunsa Campus
        dates: 2011 - 2012
        degree: B.Sc. Honours, Medical Physics
        thesis_title: 'Effect of humans on other humans: a study of human behavior.'
        thesis_url: '#'
      - college: University of the Western Cape
        dates: 2008 -2008
        degree: B.Sc. Honours, Physical Science -Material Science
      - college: North West University
        dates: 2004 - 2009
        degree: B.S. in Subject
    title: Education
  experience:
    icon: fas fa-briefcase
    list:
      - company: South African Health Products Regulatory Authority
        dates: 01 July 2021 - *Present*
        details: Regulate substances related to Group IV Hazardous substances
        position: Reviewer-Radionuclides
      - company: National Department of Health
        dates: June 2013 - June 2021
        position: Senior Admnistrative Officer
        url: '#'
    title: Experiences
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\r\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\r\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\r\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\r\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\r\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\r\n        "
    use: yes
  hobby:
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Hiking
      - hobby: Baking
    title: Hobbies
  profile:
    location: Pretoria, Arcadia, South Africa
    name: Boitshoko Phenyo Diale
    photo: profile.jpg
    tagline: 
  project:
    icon: fas fa-project-diagram
    list:
      - description: Description of the project
        title: Project 1
        url: '#'
      - description: Description of the project
        title: Project 2
        url: '#'
      - description: Description of the project
        title: Project 3
        url: '#'
      - description: Description of the project
        title: Project 4
        url: '#'
    title: Projects
  publication:
    format:
      - date
      - authors
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Proceedings
        url: '#'
    title: Publications
    types:
      - Journal Articles
      - Proceedings
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  skill:
    icon: fas fa-cogs
    list:
      - skill: Skill 1, Skill 2
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
    panelId: skill-panel
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: '#'
      
        url: '#'
      - icon: fab fa-github
        title: GitHub
        url: '#'
      - icon: fab fa-twitter
        title: Twitter
        url: '#'
      
    title: Links
  theme:
    mainTheme: ocean
    showAttribute: yes
    singlePage: no
  title: Aafu theme
